name: Build CLIUI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  debug-structure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Debug structure
      run: find . -name "gradlew" -type f

  test:
    runs-on: ubuntu-latest
    needs: debug-structure
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Test core functionality
      run: |
        if [ -d "cliui" ]; then
          cd cliui
          python test_mobile.py
          echo "✅ Mobile tests passed"
        else
          echo "❌ cliui directory not found for testing"
        fi

  android-build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Find and make gradlew executable
      run: |
        echo "Looking for gradlew..."
        # Try multiple possible locations
        if [ -f "cliui/platforms/android/gradlew" ]; then
          echo "✅ Found at: cliui/platforms/android/gradlew"
          chmod +x cliui/platforms/android/gradlew
        elif [ -f "platforms/android/gradlew" ]; then
          echo "✅ Found at: platforms/android/gradlew"
          chmod +x platforms/android/gradlew
        else
          echo "❌ gradlew not found in expected locations"
          echo "Available files:"
          find . -name "gradlew" -type f
          exit 1
        fi
        
    - name: Build Android APK
      run: |
        # Build from wherever gradlew was found
        if [ -f "cliui/platforms/android/gradlew" ]; then
          cd cliui/platforms/android
          ./gradlew assembleDebug
        elif [ -f "platforms/android/gradlew" ]; then
          cd platforms/android
          ./gradlew assembleDebug
        fi
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cliui-apk
        path: cliui/platforms/android/app/build/outputs/apk/debug/app-debug.apk
