name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Install Android SDK and Build Tools
      run: |
        sudo apt update
        sudo apt install -y android-sdk android-sdk-platform-34 android-sdk-build-tools-34-0-0 gradle
        
    - name: Build APK with Gradle
      run: gradle assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: SmartCLI-APK
        path: app/build/outputs/apk/debug/app-debug.apk
