cat > .github/workflows/android.yml << 'EOF'
name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build Debug APK
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace
        
    - name: Build F-Droid APK
      run: |
        ./gradlew assembleFdroid --stacktrace
        
    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: SmartCLI-APKs
        path: |
          app/build/outputs/apk/debug/app-debug.apk
          app/build/outputs/apk/fdroid/app-fdroid.apk
EOF
