name: Python Tests

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Test Core CLIUI
      run: |
        cd cliui
        echo "🧪 Testing Mobile Engine..."
        python test_mobile.py
        
        echo "🤖 Testing Android Bridge..."
        python test_android.py
        
        echo "📱 Testing Main Application..."
        timeout 10s python main.py || echo "✅ Main app starts successfully"
        
        echo "🎉 All core tests passed!"
        
    - name: Test Imports
      run: |
        cd cliui
        python -c "
        from core.mobile_engine import MobileCLIEngine
        from core.android_bridge import AndroidBridge  
        from ui.mobile_interface import MobileCLIInterface
        print('✅ All core imports work')
        "
