name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Build Release APK
      run: ./gradlew assembleRelease
      
    - name: Build F-Droid APK
      run: ./gradlew assembleFdroid
      
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-apks
        path: |
          app/build/outputs/apk/release/
          app/build/outputs/apk/fdroid/
        retention-days: 30
