name: Build Android APK

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev openjdk-11-jdk git zip unzip
        sudo apt-get install -y autoconf libtool pkg-config zlib1g-dev libncurses5-dev
        sudo apt-get install -y libncursesw5-dev cmake libffi-dev libssl-dev
        
    - name: Install Python packages
      run: |
        pip3 install buildozer cython python-for-android
        
    - name: Build APK
      run: |
        cd cliui/platforms/fdroid
        buildozer -v android debug
        
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: smartcli-apk
        path: cliui/platforms/fdroid/bin/*.apk
