name: Build Android APK

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          python3-dev \
          git \
          zip \
          unzip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          cmake \
          libffi-dev \
          libssl-dev
          
    - name: Install Python packages
      run: |
        pip3 install buildozer cython python-for-android
        
    - name: Build APK
      run: |
        cd cliui/platforms/fdroid
        
        # Tell Buildozer to use the existing Android SDK
        export ANDROID_SDK_ROOT="$ANDROID_SDK_ROOT"
        export ANDROID_NDK_HOME="$ANDROID_NDK_HOME"
        
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: smartcli-apk
        path: cliui/platforms/fdroid/bin/*.apk
