name: Build Android APK

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev openjdk-11-jdk git zip unzip
        sudo apt-get install -y autoconf libtool pkg-config zlib1g-dev libncurses5-dev
        sudo apt-get install -y libncursesw5-dev cmake libffi-dev libssl-dev wget curl
        
    - name: Install Buildozer
      run: pip3 install buildozer cython
        
    - name: Debug environment
      run: |
        echo "=== Environment Info ==="
        python3 --version
        pip3 --version
        java -version
        which git
        echo "========================"
        
    - name: Build with detailed logging
      run: |
        cd cliui/platforms/fdroid
        
        # Set environment variables for Buildozer
        export BUILDOZER_LOG_LEVEL=2
        
        # Clean and build with full logs
        buildozer android clean
        buildozer -v 2 android debug 2>&1 | tee full_build.log
        
        # If build fails, show the last 50 lines for quick debugging
        if [ ${PIPESTATUS[0]} -ne 0 ]; then
          echo "=== BUILD FAILED ==="
          echo "Last 50 lines of log:"
          tail -50 full_build.log
          echo "===================="
          exit 1
        fi
        
    - name: Upload full build log
      uses: actions/upload-artifact@v4
      with:
        name: full-build-log
        path: cliui/platforms/fdroid/full_build.log
        
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: smartcli-apk
        path: cliui/platforms/fdroid/bin/*.apk
