name: Build Android APK

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev openjdk-11-jdk
        sudo apt-get install -y git zip unzip autoconf libtool pkg-config
        sudo apt-get install -y zlib1g-dev libncurses5-dev libncursesw5-dev
        sudo apt-get install -y cmake libffi-dev libssl-dev wget curl build-essential
          
    - name: Install Python dependencies
      run: |
        pip3 install buildozer cython python-for-android
        
    - name: Build with detailed logging
      run: |
        cd cliui/platforms/fdroid
        export BUILDOZER_LOG_LEVEL=2
        buildozer -v android debug 2>&1 | tee full_build.log
        
        if [ ${PIPESTATUS[0]} -ne 0 ]; then
          echo "=== BUILD FAILED ==="
          tail -100 full_build.log
          exit 1
        fi
        
    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: cliui/platforms/fdroid/full_build.log
        
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: smartcli-apk
        path: cliui/platforms/fdroid/bin/*.apk
