name: Build Android APK

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install basic dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          python3-dev \
          openjdk-11-jdk \
          git \
          zip \
          unzip \
          curl \
          wget
          
    - name: Install Buildozer
      run: |
        pip3 install buildozer
        
    - name: Build with detailed logging
      run: |
        cd cliui/platforms/fdroid
        
        # Set environment for verbose logging
        export BUILDOZER_LOG_LEVEL=2
        
        echo "=== Starting Buildozer Build ==="
        buildozer -v android debug 2>&1 | tee full_build.log
        
        # If build fails, show critical errors
        if [ ${PIPESTATUS[0]} -ne 0 ]; then
          echo "=== BUILD FAILED - CRITICAL ERRORS ==="
          grep -i "error\|failed\|missing\|not found" full_build.log | head -20
          echo "=== LAST 30 LINES ==="
          tail -30 full_build.log
          exit 1
        fi
        
    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: cliui/platforms/fdroid/full_build.log
        
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: smartcli-apk
        path: cliui/platforms/fdroid/bin/*.apk
