# .github/workflows/kotlin-ci.yml
name: Kotlin CI

on:
  push:
    branches: [ main, develop, master ]
  pull_request:
    branches: [ main, develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Make gradlew executable
      run: chmod +x ./smartcli/gradlew
    
    - name: Build with Gradle
      run: |
        cd smartcli
        ./gradlew build
    
    - name: Run tests
      run: |
        cd smartcli
        ./gradlew test
    
    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: smartcli/build/reports/tests/
    
    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-reports
        path: smartcli/build/reports/
        retention-days: 7
