# .github/workflows/kotlin.yml
name: Kotlin

on:
  push:
    branches: [ main, develop, master ]
  pull_request:
    branches: [ main, develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Run tests
      run: ./gradlew test
    
    - name: Run tests with coverage
      run: ./gradlew jacocoTestReport
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results
        path: |
          build/reports/
          build/test-results/
    
    - name: Upload build reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-reports
        path: build/reports/
        retention-days: 7

  quality:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-reports
        path: build/reports/
    
    - name: Run ktlint (if configured)
      run: |
        if ./gradlew tasks | grep -q "ktlintCheck"; then
          ./gradlew ktlintCheck
        else
          echo "ktlint not configured, skipping"
        fi
    
    - name: Run detekt (if configured)
      run: |
        if ./gradlew tasks | grep -q "detekt"; then
          ./gradlew detekt
        else
          echo "detekt not configured, skipping"
        fi
    
    - name: Dependency check (if configured)
      run: |
        if ./gradlew tasks | grep -q "dependencyCheckAnalyze"; then
          ./gradlew dependencyCheckAnalyze
        else
          echo "dependencyCheck not configured, skipping"
        fi
